name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual trigger through the GitHub UI

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_PEM_KEY }}
          port: 22
          script: |
            BACKEND_PATH=${{ secrets.BACKEND_PATH }}
            FRONTEND_PATH=${{ secrets.FRONTEND_PATH }}

            echo "Navigating to backend path: $BACKEND_PATH"
            if [ ! -d "$BACKEND_PATH" ]; then
              echo "Error: Backend path does not exist!"
              exit 1
            fi

            # Deploy Backend
            cd $BACKEND_PATH
            echo "Cleaning old backend files..."
            rm -rf target/

            echo "Building backend..."
            mvn clean package -DskipTests
            if [ $? -ne 0 ]; then
              echo "Error: Backend build failed!"
              exit 1
            fi

            # Modify application-prod.properties with secrets
            echo "Updating application-prod.properties with secrets..."
            PROPERTIES_FILE="src/main/resources/application-prod.properties"

            # Check if application-prod.properties exists
            if [ ! -f "$PROPERTIES_FILE" ]; then
              echo "Error: application-prod.properties file not found!"
              exit 1
            fi

            # Run the backend with PM2
            echo "Starting backend with PM2..."
            pm2 delete dcfest-backend || true
            pm2 start "java -jar target/dc-fest-0.0.1-SNAPSHOT.jar" --name "dcfest-backend" --time

            echo "Navigating to frontend path: $FRONTEND_PATH"
            if [ ! -d "$FRONTEND_PATH" ]; then
              echo "Error: Frontend path does not exist!"
              exit 1
            fi

            # Deploy Frontend
            cd $FRONTEND_PATH
            echo "Cleaning old frontend files..."
            rm -rf dist/

            echo "Creating frontend .env file..."
            echo "VITE_APP_BACKEND_URL=${{ secrets.VITE_APP_BACKEND_URL }}" > .env

            echo "Building frontend..."
            npm install
            npm run build
            if [ $? -ne 0 ]; then
              echo "Error: Frontend build failed!"
              exit 1
            fi

            echo "Starting frontend with PM2..."
            pm2 delete dcfest-frontend || true
            pm2 serve -s dist ${{ secrets.FRONTEND_PORT }} --name "dcfest-frontend" --spa

            echo "Deployment completed successfully!"
