server.port=5006

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/dcfest_prod_p1
spring.datasource.username=harsh0811
spring.datasource.password=harsh0811

close_reg_phone=9831110762

# JWT Configurations
jwt.secret.key=ZVB7wG9c5W0Rk3sA6pI2eV8fD4lNjM7omZs3oQw8rVb2ZVB7wG9c5W0Rk3sA6pI2eV8fD4lNjM7ox4Ct6yGh11mZs3oQw>

file.upload-dir=/home/ubuntu/deploys/dcfest-app

app.prefix=/fest

# Enable SQL logging
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Log SQL statements and parameters
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ZeptoMail Configuration
zepto.url=https://api.zeptomail.in/
zepto.from=donotreply@thebges.edu.in
zepto.token=PHtE6r1ZFO/siDIooRdS4PS6RMWlYYss9L9nKgQVsI5FCv4GS00GqNkjxmS2/xktBvIWFP6Ym4k54u+et7mAJTvlMm8eX2qyqK3sx/VYSPOZsbq6x00Vt1UTcUHbVIfscNFr1SDRudbbNA==

# WhatsApp Configuration
interakt.api.key=RGY2dkVyZThGQUJ4enhXN2pRSkxJaXEzMlJaN3V3REpDQTRFbWFpMWs1WTo=
interakt.base.url=https://api.interakt.ai/v1/public/message/